version: 2
updates:
    # Maintain security for Composer dependencies
    - package-ecosystem: 'composer'
      directory: '/'
      schedule:
          interval: 'weekly'
      open-pull-requests-limit: 5

    # Maintain security for NPM dependencies
    - package-ecosystem: 'npm'
      directory: '/'
      schedule:
          interval: 'weekly'
      open-pull-requests-limit: 5
